[package]
name = "witx-bindgen-cli"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[workspace]
members = [
  "crates/test-rust-wasm",
  "crates/witx-bindgen-demo",
  "crates/wasmlink-cli",
  "crates/test-modules",
]
resolver = "2"

[[bin]]
name = "witx-bindgen"
test = false

[dependencies]
anyhow = "1.0"
structopt = { version = "0.3", default-features = false }
witx-bindgen-gen-core = { path = 'crates/gen-core', features = ['old-witx-compat'] }
witx-bindgen-gen-rust-wasm = { path = 'crates/gen-rust-wasm', features = ['structopt'] }
witx-bindgen-gen-wasmtime = { path = 'crates/gen-wasmtime', features = ['structopt'] }
witx-bindgen-gen-wasmtime-py = { path = 'crates/gen-wasmtime-py', features = ['structopt'] }
witx-bindgen-gen-js = { path = 'crates/gen-js', features = ['structopt'] }
witx-bindgen-gen-c = { path = 'crates/gen-c', features = ['structopt'] }
witx-bindgen-gen-markdown = { path = 'crates/gen-markdown', features = ['structopt'] }
witx-bindgen-gen-spidermonkey = { path = 'crates/gen-spidermonkey', features = ['structopt'] }
witx-bindgen-gen-wasmer = { path = 'crates/gen-wasmer', features = ['structopt'] }

# Compiling `spidermonkey.wasm` takes way too long without this.
[profile.dev.package.cranelift-codegen]
debug-assertions = false
opt-level = 2
