[package]
name = "wit-bindgen-cli"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
description = "Generate glue code for *.wit files"

[workspace]
members = [
  "crates/test-rust-wasm",
  "crates/wit-bindgen-demo",
  "crates/wit-component",
]
resolver = "2"

[[bin]]
name = "wit-bindgen"
test = false

[dependencies]
anyhow = "1.0"
structopt = { version = "0.3", default-features = false }
wit-bindgen-gen-core = { path = 'crates/gen-core' }
wit-bindgen-gen-rust-wasm = { path = 'crates/gen-rust-wasm', features = ['structopt'] }
wit-bindgen-gen-wasmtime = { path = 'crates/gen-wasmtime', features = ['structopt'] }
wit-bindgen-gen-wasmtime-py = { path = 'crates/gen-wasmtime-py', features = ['structopt'] }
wit-bindgen-gen-js = { path = 'crates/gen-js', features = ['structopt'] }
wit-bindgen-gen-c = { path = 'crates/gen-c', features = ['structopt'] }
wit-bindgen-gen-markdown = { path = 'crates/gen-markdown', features = ['structopt'] }
wit-bindgen-gen-spidermonkey = { path = 'crates/gen-spidermonkey', features = ['structopt'] }
wit-bindgen-gen-wasmer = { path = 'crates/gen-wasmer', features = ['structopt'] }
wit-bindgen-gen-wasmer-py = { path = 'crates/gen-wasmer-py', features = ['structopt'] }

# Compiling `spidermonkey.wasm` takes way too long without this.
[profile.dev.package.cranelift-codegen]
debug-assertions = false
opt-level = 2

[package.metadata.wapm]
namespace = "Michael-F-Bryan"
abi = "wasi"

[package.metadata.wapm.fs]
"."="."
