# cargo publish --manifest-path="$(pwd)/crates/parser/Cargo.toml"
# cargo publish --manifest-path="$(pwd)/crates/gen-core/Cargo.toml"
# cargo publish --manifest-path="$(pwd)/crates/wit-component/Cargo.toml"
# cargo publish --allow-dirty --manifest-path="$(pwd)/crates/gen-rust/Cargo.toml"
# cargo publish --allow-dirty --manifest-path="$(pwd)/crates/gen-rust-wasm/Cargo.toml"
# cargo publish --allow-dirty --manifest-path="$(pwd)/crates/rust-wasm-impl/Cargo.toml"
# cargo publish --allow-dirty --manifest-path="$(pwd)/crates/rust-wasm/Cargo.toml"
