[package]
name = "test-helpers"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
publish = false
license = "MIT"
description = "wit-bindgen-gen-c"

[lib]
proc-macro = true
doctest = false
test = false

[dependencies]
backtrace = "0.3"
heck = "0.3"
ignore = "0.4"
proc-macro2 = "1.0.27"
quote = "1.0.9"
wit-bindgen-gen-core = { path = '../gen-core' }
wit-bindgen-gen-rust-wasm = { path = '../gen-rust-wasm', optional = true }
wit-bindgen-gen-wasmtime = { path = '../gen-wasmtime', optional = true }
wit-bindgen-gen-wasmtime-py = { path = '../gen-wasmtime-py', optional = true }
wit-bindgen-gen-js = { path = '../gen-js', optional = true }
wit-bindgen-gen-c = { path = '../gen-c', optional = true }
wit-bindgen-gen-spidermonkey = { path = '../gen-spidermonkey', optional = true }
wit-bindgen-gen-wasmer = { path = '../gen-wasmer', optional = true }
wit-bindgen-gen-wasmer-py = { path = '../gen-wasmer-py', optional = true }
wit-parser = { path = '../parser' }
filetime = "0.2"

[build-dependencies]
wit-bindgen-gen-c = { path = '../gen-c' }
wit-bindgen-gen-spidermonkey = { path = '../gen-spidermonkey' }
wit-bindgen-gen-core = { path = '../gen-core' }

[features]
default = ['wasm-rust', 'wasm-c', 'wasm-spidermonkey']
wasm-rust = []
wasm-c = []
wasm-spidermonkey = []
