[package]
name = "wit-bindgen-rust"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "MIT"
description = "wit-bindgen-gen-c"

[dependencies]
wai-bindgen-rust-impl = { path = "../rust-wasm-impl", version = "0.2.1", optional = true }
async-trait = { version = "0.1.51", optional = true }
bitflags = "1.3"

[features]
default = ["macros", "async"]
macros = ["wai-bindgen-rust-impl"]
async = ["async-trait"]
