[package]
name = "wit-bindgen-rust"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Rust WASM generator for WIT"

[dependencies]
wit-bindgen-rust-impl = { path = "../rust-wasm-impl", optional = true }
async-trait = { version = "0.1.51", optional = true }
bitflags = "1.3"

[features]
default = ["macros", "async"]
macros = ["wit-bindgen-rust-impl"]
async = ["async-trait"]
