[package]
name = "wit-bindgen-gen-rust"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "MPL-2.0"
description = "WIT bindgen generator for Rust code"

[lib]
doctest = false
test = false

[dependencies]
wai-bindgen-gen-core = { path = "../gen-core", version = "0.2.1" }
heck = "0.3"
