[package]
name = "wit-bindgen-gen-core"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "MIT"
description = "wit-bindgen-gen-c"

[lib]
doctest = false

[dependencies]
wit-parser = { path = '../parser' }
anyhow = "1"
