[package]
name = "wasmer-wit-bindgen-gen-core"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "Apache-2.0"
description = "wit-bindgen-gen-c"

[lib]
doctest = false

[dependencies]
wasmer-wit-parser = { version = "0.1.0", path = '../parser' }
anyhow = "1"
