[package]
name = "wai-component"
authors = ["Peter Huene <peter@huene.dev>"]
edition = "2021"
license = "MIT"
description = "wit-bindgen-gen-c"

[[bin]]
name = "wai-component"
path = "src/bin/wai-component.rs"
required-features = ["cli"]

[[bin]]
name = "wit2wasm"
path = "src/bin/wit2wasm.rs"
required-features = ["cli"]

[[bin]]
name = "wasm2wit"
path = "src/bin/wasm2wit.rs"
required-features = ["cli"]

[dependencies]
wasmparser = "0.86.0"
wasm-encoder = "0.13.0"
wat = "1.0.44"
wai-parser = { path = "../parser", version = "0.2.1" }
anyhow = "1.0.55"
indexmap = "1.8.0"
clap = { version = "3.1.0", features = ["derive"], optional = true }
env_logger = { version = "0.9.0", optional = true }
log = { version = "0.4.14", optional = true }

[dev-dependencies]
wasmprinter = "0.2.36"
glob = "0.3.0"
pretty_assertions = "1.2.0"

[features]
default = ["cli"]
cli = ["clap", "env_logger", "log"]
